on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Build

jobs:
  release:
    name: Release version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # build here
        # testing here
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: LICENSE